import {
  ArrowDown,
  ArrowDownWideNarrow,
  ArrowRight,
  ArrowUp,
  ArrowUpNarrowWide,
  ChartLine,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  Download,
  ClipboardList,
  Dumbbell,
  Eye,
  EyeOff,
  Flag,
  History,
  House,
  Link2,
  Lock,
  LogOut,
  Minus,
  Pencil,
  Play,
  Plus,
  RotateCcw,
  Search,
  Timer,
  Trash2,
  Undo2,
  User,
  X,
} from 'lucide';

/* Le icone che l'app disegna, e nessun'altra: chi ne vuole una nuova la aggiunge qui. */
export const ICONS = {
  logo: Dumbbell,
  home: House,
  plans: ClipboardList,
  exercises: Dumbbell,
  history: History,
  stats: ChartLine,
  plus: Plus,
  minus: Minus,
  trash: Trash2,
  edit: Pencil,
  close: X,
  check: Check,
  up: ArrowUp,
  down: ArrowDown,
  submit: ArrowRight,
  prev: ChevronLeft,
  next: ChevronRight,
  collapse: ChevronUp,
  expand: ChevronDown,
  timer: Timer,
  play: Play,
  finish: Flag,
  reopen: RotateCcw,
  logout: LogOut,
  alert: CircleAlert,
  undo: Undo2,
  eye: Eye,
  eyeOff: EyeOff,
  lock: Lock,
  user: User,
  // per i pezzi presi da restaurant-index
  link: Link2,
  search: Search,
  sortAsc: ArrowUpNarrowWide,
  sortDesc: ArrowDownWideNarrow,
  download: Download,
} as const;

export type IconName = keyof typeof ICONS;
